version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html

hooks:
  AfterInstall:
    - location: scripts/start_nginx.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_nginx.sh
      timeout: 300
      runas: root